apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-deployment
  labels: 
     app: demo-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: app
        image: trainerforaws/application
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
